version: "2.4"
# This server profile used as basis for ping-devop docker-launch

#-------------------------------------------------------------------------------------
#- Ping Identity PingDirectory getting started demo
#-
#-                          +---------------+
#-                          |PingDataConsole|
#-                          +---------------+
#-                                  |
#-                          +----------------+
#-                          | PingDirectory  |
#-                          +----------------+
#-
#- To view PingData Console goto:
#-
#-    https://localhost:8443/
#-
#-      Server: pingdirectory:1636
#-    Username: administrator
#-    Password: 2FederateM0re
#-
#- To view users in Ping Directory (via REST) goto:
#-    https://localhost:1443/directory/v1/ou=people,dc=example,dc=com/subtree?searchScope=singlelevel
#-
#-    Username: cn=administrator
#-    Password: 2FederateM0re
#-------------------------------------------------------------------------------------

services:
  pingdirectory:
    image: pingidentity/pingdirectory:9.0.0.0-EA-alpine_3.14-al11-edge
    # You may need to comment this tmpfs line if you run containers on windows
    tmpfs: /run/secrets
    env_file:
      - ${HOME}/.pingidentity/devops
    environment:
      - SERVER_PROFILE_URL=https://github.com/arnaudlacour/stellantis.git
      - GENERATED_CONSUMERS=1000000
      - MAX_HEAP_SIZE=4g
      - USER_BASE_DN=o=stellantis.com
    networks:
      - pingnet
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "1389:1389"
      - "1636:1636"
      - "1443:1443"
    volumes:
      - pingdirectory-out:/opt/out

  pingdataconsole:
    image: pingidentity/pingdataconsole:9.0.0.0-EA-alpine_3.14-al11-edge
    ports:
      - "8443:8443"
    networks:
      - pingnet

#  searchrate:
#    image: pingidentity/ldap-sdk-tools:edge
#    command: wait-for pingdirectory:1389 -t 600 -- searchrate --hostname pingdirectory --port 1389 --bindDN uid=admin,o=stellantis.com --bindPasswordFile /opt/staging/.sec/root-user-password --baseDN "ou=consumers,o=stellantis.com" --scope sub --filter "(&(objectClass=person)(mail=*@gmail.com*)" --numThreads 2
#    network:
#      - pingnet
#    volumes:
#      - pingdirectory-out:/opt/out
    

networks:
  pingnet:

volumes:
  pingdirectory-out:
